// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II Version 10.0 (Build Build 218 06/27/2010)
// Created on Sat Apr 28 20:56:11 2018

lab2_3 lab2_3_inst
(
	.clock(clock_sig) ,	// input  clock_sig
	.cclr(cclr_sig) ,	// input  cclr_sig
	.c0(c0_sig) ,	// input  c0_sig
	.a(a_sig) ,	// input [31:0] a_sig
	.b(b_sig) ,	// input [31:0] b_sig
	.carry_out3(carry_out3_sig) ,	// output  carry_out3_sig
	.out(out_sig) 	// output [31:0] out_sig
);

