# Generated by Django 3.0.4 on 2024-12-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20241217_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publish_data',
            new_name='publish_date',
        ),
    ]
